version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build:
      context: ./tic-tac-toe
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
